# Generated by Django 5.1.3 on 2024-11-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costumuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
