# Generated by Django 5.1.3 on 2024-12-03 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_costumuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="costumuser",
            name="Your_major_type",
            field=models.CharField(
                choices=[
                    ("flutter", "flutter"),
                    ("Ui/Ux", "Ui/Ux"),
                    ("Graphic_Design", "Graphic_Design"),
                    ("Civil_Engineering", "Civil_Engineering"),
                    ("Android_Developer", "Android_Developer"),
                    ("Django", "Django"),
                    ("HR", "HR"),
                ],
                default="your_major_tupe",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="costumuser",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("None", "None")],
                default="None",
                help_text="Gender",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.TextField(help_text="New post", max_length=1000)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
